apiVersion: app/v1

kind: Deployment

metadata:
  name: sample-cd-deployment

spec:
  replicas:
  selector:
    matchLabels:
      app: sample-cd-app
    template:
      metadata:
        lables:
          app: sample-cd-app
      spec:
        containers:
        - name: nginx-container
          image: nginx
